# Generated by Django 3.1.6 on 2021-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='groupId',
            field=models.IntegerField(default=0),
        ),
    ]
