# Generated by Django 3.1.6 on 2021-02-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='technicianId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tecnician'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='custId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='groupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productgroup'),
        ),
    ]
