# Generated by Django 3.1.6 on 2021-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210211_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Promotion Code')),
                ('promoType', models.CharField(choices=[('Unit', 'Unit'), ('Quantity', 'Qty')], default='Unit', max_length=8)),
                ('minValue', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Amount in percent')),
                ('status', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='installationDate',
            field=models.DateTimeField(null=True, verbose_name='Installation Date'),
        ),
    ]
