# Generated by Django 3.1.6 on 2021-02-12 08:26

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210212_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderNo',
            field=models.CharField(default=app.models.Orders.increment_invoice_number, max_length=255, verbose_name='Order Number'),
        ),
    ]
