# Generated by Django 3.1.6 on 2021-02-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='promotionCode',
            field=models.CharField(max_length=10, null=True, verbose_name='Promotion Code'),
        ),
    ]
